src/objects/Item__c.object
<CustomObject>
    <description>Items for sale.</description>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>The item price.</description>
        <label>Price</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Order__c.object
<CustomObject>
    <description>An order that contains buyer information and line items.</description>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{0000}</displayFormat>
        <label>Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/StoreExtensionTest.cls
@isTest
private class StoreExtensionTest {
	
	@isTest static void testAddToCart() {
		Item__c item = new Item__c(Name = 'Test Item', Price__c = 10, Is_Active__c = true);
		insert item;

		Order__c order = new Order__c(Total__c = 0);
		insert order;

		ApexPages.currentPage().getParameters().put('itemId', item.Id);

		StoreExtension se = new StoreExtension(new ApexPages.StandardController(order));

		// Get the items
		System.assert(se.items.size() == 1);

		// Add to Cart
		se.addtoCart();
		System.assert(order.Total__c == 10);
	}
	
	@isTest static void testHelperMethods() {
		StoreExtension se = new StoreExtension();

		se.toggleShowCart();
		System.assert(se.showCart);
		System.assert(se.getToggleLink().equals('Hide Cart'));

		System.assert(se.gotoCheckout().getUrl() == Page.Checkout.getUrl(), se.gotoCheckout());
		System.assert(se.continueShopping().getUrl() == Page.Store.getUrl(), se.continueShopping());
		System.assert(se.completeOrder().getUrl() == Page.OrderSummary.getUrl(), se.completeOrder());
	}
}